joint_limits:
  joint1:
    lower: -2.6179938
    upper: 2.6179938
    effort: 100
    velocity: 5
  joint2:
    lower: -0.26
    upper: 3.35
    effort: 100
    velocity: 5
  joint3:
    lower: -2.9670597
    upper: 0.05
    effort: 100
    velocity: 5
  joint4:
    lower: -2.368
    upper: 2.368
    effort: 100
    velocity: 5
  joint5:
    lower: -1.2217304
    upper: 1.2217304
    effort: 100
    velocity: 5
  joint6:
    lower: -6.25
    upper: -1.95
    effort: 100
    velocity: 5